In [1]:
import numpy as np
P = np.array([[0.2, 0.3, 0.5],
              [0.4, 0.2, 0.4],
              [0.1, 0.6, 0.3]])

In [36]:

def stationary_distrib(P):
    # Transpose of the transition matrix
    P_transpose = P.T

    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(P_transpose)
    print(eigenvalues, eigenvectors)
    # Find the index of the eigenvalue 1
    index_of_unity = np.where(np.isclose(np.abs(eigenvalues), 1,0.01076))[0][0]

    # Corresponding eigenvector is the stationary distribution
    stationary_distribution = np.real(eigenvectors[:, index_of_unity])
    stationary_distribution /= stationary_distribution.sum()

    # Verify that pi P = pi
    result = np.dot(stationary_distribution, P)
    return (stationary_distribution)

In [35]:
stationary_distribution=stationary_distrib(P)
print(stationary_distribution)
pi=stationary_distribution

[ 1.  +0.j         -0.15+0.16583124j -0.15-0.16583124j] [[ 0.40223738+0.j         -0.54554473-0.36187343j -0.54554473+0.36187343j]
 [ 0.64106583+0.j          0.65465367+0.j          0.65465367-0.j        ]
 [ 0.65363575+0.j         -0.10910895+0.36187343j -0.10910895-0.36187343j]]
[0.23703704 0.37777778 0.38518519]


In [10]:
##calculate time reverse counter part
P_r=np.copy(P)
for i in range(len(P)):
    for j in range(len(P[0])):
        P_r[i][j]=P[i][j]*pi[j]/pi[i]
stat_dist_P_r=stationary_distrib(P_r)
print(stationary_distribution,stat_dist_P_r)

[0.23703704 0.37777778 0.38518519] [0.16179491 0.4109654  0.42723969]


In [7]:
print("P=",P)
print("P_r=",P_r)

P= [[0.2 0.3 0.5]
 [0.4 0.2 0.4]
 [0.1 0.6 0.3]]
P_r= [[0.2        0.478125   0.8125    ]
 [0.25098039 0.2        0.40784314]
 [0.06153846 0.58846154 0.3       ]]


In [38]:
# Q=P+P_r
# Q=np.array(Q/2)
# print(Q)
stat_dist_Q=stationary_distrib(Q)
print(stat_dist_Q)
print(np.matmul(stat_dist_Q,Q))


[ 1.01076+0.j         -0.15538+0.17406139j -0.15538-0.17406139j] [[ 0.33093427+0.j         -0.46135621-0.32059476j -0.46135621+0.32059476j]
 [ 0.65599036+0.j          0.70480575+0.j          0.70480575-0.j        ]
 [ 0.67835032+0.j         -0.11944428+0.41635486j -0.11944428-0.41635486j]]
[0.1987265  0.39392316 0.40735034]
[0.2008648  0.39816177 0.41173343]
