In [53]:
import numpy as np
from numpy.linalg import matrix_power
P=np.array([[1/3,1/3,1/3],
   [1/3,1/3,1/3],
   [1/3,1/3,1/3]])
P_T=P.T
D=np.multiply(P,P_T)
D=np.sqrt(D)
print("P=",P)
print("D=",D)


P= [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
D= [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


# calculating V

In [54]:
# one hot vector
def One_Hot_vector(a,l):
    vec=[]
    for i in range(l):
        if(i==a):
            vec.append(1)
        else:
           vec.append(0)
    return(np.transpose(np.array(vec)))
print(One_Hot_vector(0,3))

[1 0 0]


In [55]:
V_i=[] ##it has all the V_i s
for i in range(len(P)):
    u=[]
    for j in range(len(P)):
        u.append([np.sqrt(P[i][0]),np.sqrt(P[i][1]),np.sqrt(P[i][2])])
    V_i.append(u)
V=[]
for i in range(9):
    t=[]
    for j in range(9):
        t.append(0)
    V.append(t)
for r in range(len(P)):
    i=One_Hot_vector(r,3)
    # print(i)
    temp=np.outer(i,i)
    print(temp)
    temp=np.kron(temp,V_i[r])
    # print(temp)
    V=V+temp
print(V)


[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0.57735027 0.57735027 0.57735027 0.         0.         0.
  0.         0.         0.        ]
 [0.57735027 0.57735027 0.57735027 0.         0.         0.
  0.         0.         0.        ]
 [0.57735027 0.57735027 0.57735027 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.57735027 0.57735027 0.57735027
  0.         0.         0.        ]
 [0.         0.         0.         0.57735027 0.57735027 0.57735027
  0.         0.         0.        ]
 [0.         0.         0.         0.57735027 0.57735027 0.57735027
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.57735027 0.57735027 0.57735027]
 [0.         0.         0.         0.         0.         0.
  0.57735027 0.57735027 0.57735027]
 [0.         0.         0.         0.         0.         0.
  0.57735027 0.57735027 0.57735027]]


In [56]:
##S matrix creation
S=[]
for i in range(9):
    temp=[]
    for j in range(9):
        temp.append(0)
    S.append(temp)
a=0
for i in range(len(P)):
    for j in range(len(P[i])):
        if(P[i][j]>0):
            b=j*3+i
            print(a,b)
            S[a][b]=1
        else:
            S[a][a]=1
        a=a+1
print(S)

0 0
1 3
2 6
3 1
4 4
5 7
6 2
7 5
8 8
[[1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1]]


In [65]:
##compute U, pi_b ,W matrix
V_dagger=V.T
U=np.matmul(S,V)
U=np.matmul(V_dagger,U)
b=One_Hot_vector(0,3)
v=np.array([1,1,1])
vb=np.kron(v,b)
print(vb)
I=np.identity(3)
b_b=np.outer(b,b)
Pi_b=np.kron(I,b_b)
W=np.matmul(2*Pi_b-np.identity(len(Pi_b)),U)

#one step walk
fin=np.matmul(Pi_b,np.matmul(W,vb))
print(fin)

#2 step walk
fin=np.matmul(Pi_b,np.matmul(np.square(W),vb))
print(fin)


[1 0 0 1 0 0 1 0 0]
[1. 0. 0. 1. 0. 0. 1. 0. 0.]
[0.33333333 0.         0.         0.33333333 0.         0.
 0.33333333 0.         0.        ]
